remove in workflow update
blacs30/bitwarden-alfred-workflow pull request #161
Opened 2023-06-17 18:05 UTC by zhongjis

- fix README.md fix line breakers
- remove update options in `.bwconf` 1. remove option code 2. remove update icons 3. update readme.md

2023-06-17 19:26 UTC, zhongjis commented
@blacs30 
for some reason the change does not reflect on my new build generated using `make universal-binary`. wondering if you got any insight on this. does this relate to my go setting?


![Screenshot 2023-06-17 at 12 05 10](https://github.com/blacs30/bitwarden-alfred-workflow/assets/23202735/7d8a53e2-9664-4429-9501-99071a6e202f)

2023-06-24 16:59 UTC, zhongjis commented
tuned out my build was having some typos. now it should be fixed
<img width="631" alt="Screenshot 2023-06-24 at 12 58 03" src="https://github.com/blacs30/bitwarden-alfred-workflow/assets/23202735/dcf65dfa-14e4-4a82-8b8c-bfa9afd00388">

2023-06-24 16:59 UTC, zhongjis commented
@blacs30 let me know if im missing anything

2023-06-28 21:54 UTC, blacs30 requested changes
sorry, haven't submitted my review when I made it

2023-07-02 08:36 UTC, zhongjis commented on src/cli.go
> +		Vas("notification", "Downloading Favicons for URLs").
seems like I forgot to push my latest changes. it is fixed

2023-07-03 07:52 UTC, blacs30 approved these changes

2023-07-03 22:31 UTC, merged